# Generated by Django 5.2.7 on 2026-01-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('var1', models.FloatField()),
                ('var2', models.IntegerField()),
                ('var3', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='vars_messag_timesta_25290d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_var', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='vars_trends_timesta_3fbd1c_idx'), models.Index(fields=['id_var'], name='vars_trends_id_var_9f594c_idx')],
            },
        ),
    ]
