# Generated by Django 5.2.7 on 2025-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_var', models.IntegerField()),
                ('Value', models.FloatField()),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
    ]
